mytestkey=This value is from LOCAL properties file

stripe.api.key=sk_test_51SyUNSJYjaCNcfJGdS1hQ8Nbbs7TFzOPNqaFGBXPOygodKeybORZl5s3zZGkgRNbFtMPSAkDKbFoBNwMV5JQ42of00hwW0eedM
stripe.create.session.url=https://api.stripe.com/v1/checkout/sessions