spring.profiles.active=@spring.profiles.active@

server.port=8083

spring.application.name=stripe-provider-service

stripe.secret.key=${STRIPE_SECRET_KEY:}
stripe.checkout.session.url=https://api.stripe.com/v1/checkout/sessions

logging.level.com.mycompany.payments=INFO
